export const FETCH_EXERCISE_STARTED = 'FETCH_EXERCISE_STARTED';
export const FETCH_EXERCISE_FAILED = 'FETCH_EXERCISE_FAILED';
export const FETCH_EXERCISE_COMPLETED = 'FETCH_EXERCISE_COMPLETED';

export const PROGRESS_EXERCISE_STARTED = 'PROGRESS_EXERCISE_STARTED';
export const PROGRESS_EXERCISE_FAILED = 'PROGRESS_EXERCISE_FAILED';
export const PROGRESS_EXERCISE_COMPLETED = 'PROGRESS_EXERCISE_COMPLETED';