export const SUBMIT_INITIAL_TEST_STARTED = 'SUBMIT_INITIAL_TEST_STARTED';
export const SUBMIT_INITIAL_TEST_COMPLETED = 'SUBMIT_INITIAL_TEST_COMPLETED';
export const SUBMIT_INITIAL_TEST_FAILED = 'SUBMIT_INITIAL_TEST_FAILED';