export const SUBMIT_TUTORIAL_STARTED = 'SUBMIT_TUTORIAL_STARTED';
export const SUBMIT_TUTORIAL_COMPLETED = 'SUBMIT_TUTORIAL_COMPLETED';
export const SUBMIT_TUTORIAL_FAILED = 'SUBMIT_TUTORIAL_FAILED';

export const SUBMIT_INITIAL_TEST_STARTED = 'SUBMIT_INITIAL_TEST_STARTED';
export const SUBMIT_INITIAL_TEST_COMPLETED = 'SUBMIT_INITIAL_TEST_COMPLETED';
export const SUBMIT_INITIAL_TEST_FAILED = 'SUBMIT_INITIAL_TEST_FAILED';

export const SUBMIT_FINAL_TEST_STARTED = 'SUBMIT_FINAL_TEST_STARTED';
export const SUBMIT_FINAL_TEST_COMPLETED = 'SUBMIT_FINAL_TEST_COMPLETED';
export const SUBMIT_FINAL_TEST_FAILED = 'SUBMIT_FINAL_TEST_FAILED';
