name: Check for coverage

on:
  pull_request:
    branches:
      - main

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install and run tests
        run: |
          yarn install
          yarn test --coverage --watchAll