name: Check for coverage

on:
  push:
    branches:
      - feature/ci-pipeline

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        run: yarn install

      - uses: artiomtr/jest-coverage-report-action@v2
        with:
          package-manager: yarn
          test-script: yarn jest --ci --json --coverage --testLocationInResults --outputFile=report.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-step: install