name: Check for coverage

on:
  pull_request:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 'Manual installation'
        run: yarn install

      - name: 'Run tests'
        run: yarn yarn test --coverage --watchAll